### PR TITLE
Fix Tempo url config in Grafana

### PR DESCRIPTION
**Pull request by scorsi**

### CODE REVIEW

**Comment by cyriltovena** [comment]
I'm using the latest tempo and I think the url is correct ?

**Comment by scorsi** [comment]
Hello @cyriltovena I confirme that with `/tempo` at the url, requests doesn't work with last version of both Grafana and Tempo.
And it's also your case in your screencast https://youtu.be/dCG0eRZb6qg?t=1152

**Comment by cyriltovena** [comment]
I'll take a second look then !

**Review by cyriltovena — APPROVED** [review]
LGTM

**Pull request merged**
